name: env_tutorial

# Triggers the workflow when there is a push or pull request on the main branch
on: 
  - pull_request
  - push

env:
  # Sets environment variable
  API_KEY: XXXXXXXXXXXX

jobs:
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
